data_ingestion:
  bucket_name : "mlops-p-2-data"
  bucket_file_names:
    - "anime.csv"
    - "anime_with_synopsis.csv"
    - "animelist.csv"
    
model:
  embedding_size: 64
  loss : binary_crossentropy
  optimizer : Adam
  metrics : ['mae','mse']
  
